services:
  Image_Upload_Service:
    build:
      context: ./image_upload_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  ML_Classification_Service:
    build:
      context: ./ml_classification_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - image_upload

  Notification_Service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - ml_classification
