name: Deploy to Docker Hub and Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          # Tag each service with the Docker Hub repository name
          docker tag image_upload_service:latest ${{ secrets.DOCKER_USERNAME }}/image_upload_service:latest
          docker tag ml_classification_service:latest ${{ secrets.DOCKER_USERNAME }}/ml_classification_service:latest
          docker tag notification_service:latest ${{ secrets.DOCKER_USERNAME }}/notification_service:latest

      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/image_upload_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ml_classification_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notification_service:latest



          
      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'  

      # - name: Install Railway CLI
      #   run: |
      #     npm install -g @railway/cli
      # - name: Deploy to Railway
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  
      #   run: |
      #     railway up --service "Image_Upload_Service"
      
